---
- hosts: all 
  gather_facts: True

  task:
    - name: Installing java(jdk)  CentOS
      yum: pkg=java-1.7.0-openjdk state=latest
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Installing java(jdk)  Ubuntu
      apt: pkg=openjdk-7-jre-headless state=present 
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install apache ubuntu
      apt: pkg=apache2 state=present update_cache=yes cache_valid_time=86400
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install apache CentOS
      yum: pkg=httpd state=latest update_cache=yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: start apache
      service: name=apache2 state=started

    - name: start httpd
      service: name=httpd state=started

    - name: restart apache
      service: name=apache2 state=restarted

    - name: restart httpd
      service: name=httpd state=restarted

